### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by xkhainguyen** [RoboticExplorationLab/RobotZoo.jl#9]
So many tiny issues with the example, I try to fix it but I think you can help me:
1. `model RobotZoo.Cartpole()`
=> `model = RobotZoo.Cartpole()`
2. `using` doesn't allow to ignore namespace. 
=> Still have to use `RobotDynamics.dynamics()`
3. `jacobian!()` doesn't work. 
> ERROR: MethodError: no method matching jacobian!(::RobotDynamics.DynamicsJacobian{4, 5, Float64}, ::RobotZoo.Cartpole{Float64, 5}, ::KnotPoint{4, 1, StaticArraysCore.SVector{5, Float64}, Float64})
Closest candidates are:
  jacobian!(::RobotDynamics.FunctionInputs, ::RobotDynamics.AbstractFunction, ::Any, ::Any, ::RobotDynamics.AbstractKnotPoint) at C:\Users\nxk12\.julia\packages\RobotDynamics\baZMh\src\functionbase.jl:251

=> Try `RobotDynamics.jacobian!(model, ∇f, ẋ, z)` instead, another error
>ERROR: NotImplementedError: User-defined Jacobian not implemented for RobotZoo.Cartpole{Float64, 5}

4. `x′ = RobotDynamics.discrete_dynamics(model, RK3, z)` doesn't work.
> ERROR: MethodError: no method matching discrete_dynamics(::Type{RobotDynamics.RK3}, ::RobotZoo.Cartpole{Float64, 5}, ::KnotPoint{4, 1, StaticArraysCore.SVector{5, Float64}, Float64})
Closest candidates are:
  discrete_dynamics(::RobotDynamics.DiscretizedDynamics, ::Any, ::Any, ::Any, ::Any) at C:\Users\nxk12\.julia\packages\RobotDynamics\baZMh\src\discretized_dynamics.jl:203

=> It asks to define `DiscretizedDynamics` before?

I hope you can help me to clean these stuff, for others as well. Thanks.

**Comment by bjack205** [comment]
If you're referring to the example in the README, it's now been updated to reflect the new RobotDynamics API.

**Comment by xkhainguyen** [comment]
### Package Version
  [38ceca67] RobotDynamics v0.4.7 `https://github.com/RoboticExplorationLab/RobotDynamics.jl.git#master`
  [74be38bb] RobotZoo v0.3.2 `https://github.com/RoboticExplorationLab/RobotZoo.jl.git#master`
  [c79d492b] TrajectoryOptimization v0.7.0 `https://github.com/RoboticExplorationLab/TrajectoryOptimization.jl.git#main`

### Julia Version
1.6.7

### OS
Windows 11

### Describe the bug
`RD.jacobian!(RD.StaticReturn(), RD.ForwardAD(), model, ∇f, ẋ, model, z)` => no match
`x′ = RD.discrete_dynamics(dmodel, model, x, u, t, dt)` => no match
`RD.discrete_jacobian!(RD.StaticReturn(), RD.ForwardAD(), dmodel, ∇f, x′, z)` => not defined

### My fixes
`RD.jacobian!(RD.StaticReturn(), RD.ForwardAD(), model, ∇f, ẋ, z)`
`x′ = RD.discrete_dynamics(dmodel, x, u, t, dt)`
The third line is still unsolved. Could you show me how to fix it?

Thank you for spending time helping me out!
